spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/code/configrepo
          fail-fast: true

  application:
    name:
      spring-cloud-config-server

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
