server:
  port: 8888 # commonly used port for spring cloud config server by convention

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rgradison/spring-cloud-config-server.git
          default-label: master
          clone-on-start: true
          fail-fast: true
  application:
    name: spring-cloud-config-server

#This aint good for production
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO